import { initNauticalDepth, setNauticalDepthTheme } from './depth.js';

const MAPTILER_API_KEY='72WUquDNJCLDzyB9DSky'; // Publik klientnyckel. Begränsa till appens domän i MapTiler.
const CACHE_KEY='hummerkartan:state:v2';
const PENDING_KEY='hummerkartan:pending:v2';
const TRIP_KEY='hummerkartan:activeTrip:v2';
const PLAN_CACHE_PREFIX='hummerkartan:plan:v2:';
const HEAT_CACHE_KEY='hummerkartan:heat:v2';
const AUTH_DEVICE_KEY='hummerkartan:auth-device:v1';
const WEST_COAST_CENTER=[11.45,58.15];
const START_ZOOM=8.2;
const NAV_ZOOM=14.2;
const DESKTOP_BREAKPOINT=900;

const $=id=>document.getElementById(id);
const state={traps:[],checks:[],trips:[],user:'familj',serverTime:null};
let map=null,boatMarker=null,watchId=null,currentPosition=null,currentAccuracy=null,lastPosition=null,lastPositionAt=0;
let trapMarkers=new Map(),planMarkers=new Map(),selectedTrapId=null,selectedSpotId=null,navigationTarget=null;
let roundActive=false,roundVisited=new Set(),roundSequence=[];
let activeTrip=loadJson(TRIP_KEY,null),tripPoints=[],trackBatch=[],trackSeq=0,tripDistanceNm=0;
let theme=localStorage.getItem('hummerkartan:theme')==='night'?'night':'day';
let filterActiveOnly=true,desktopFilterActive=true,desktopSearch='',toastTimer=null,syncTimer=null;
let dayPlan={date:localDateKey(),plan:null,items:[]},planDirty=false,placementMode=null,placementReturn=null,planSaveTimer=null,pendingSpotConversionId=null;
let planRevision=0,planSaveInFlight=false,planLastSyncedAt=0,planConflictDates=new Set();
let heatData=loadJson(HEAT_CACHE_KEY,{points:[],totals:{checks:0,lobsters:0,average:0}}),heatmapVisible=false;
let historyTripId=null;

function loadJson(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function saveJson(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function isoNow(){return new Date().toISOString()}
function localDateKey(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
function fmtDate(value){if(!value)return 'Inte ännu';const d=new Date(value);return Number.isNaN(d.valueOf())?'—':d.toLocaleString('sv-SE',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function fmtClock(value){if(!value)return '—';const d=new Date(value);return d.toLocaleTimeString('sv-SE',{hour:'2-digit',minute:'2-digit'})}
function fmtDay(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.valueOf())?'—':d.toLocaleDateString('sv-SE',{year:'numeric',month:'short',day:'numeric'})}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function toRad(d){return d*Math.PI/180}
function toDeg(r){return r*180/Math.PI}
function distanceNm(a,b){if(!a||!b)return Infinity;const R=3440.065,lat1=toRad(a.lat),lat2=toRad(b.lat),dLat=lat2-lat1,dLon=toRad(b.lon-a.lon);const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(h)))}
function bearingDeg(a,b){if(!a||!b)return null;const p1=toRad(a.lat),p2=toRad(b.lat),dl=toRad(b.lon-a.lon);const y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return (toDeg(Math.atan2(y,x))+360)%360}
function knots(ms){return Number.isFinite(ms)?ms*1.943844:null}
function isDesktop(){return window.innerWidth>=DESKTOP_BREAKPOINT}
function toast(text,ms=2400){const el=$('toast');if(!el)return;el.textContent=text;el.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.add('hidden'),ms)}
function setSync(text,ok=true){for(const id of ['syncText','desktopSyncText']){const el=$(id);if(el){el.textContent=text;el.style.color=ok?'':'#e9a18f'}}}

function setTheme(next){
  theme=next==='night'?'night':'day';localStorage.setItem('hummerkartan:theme',theme);document.body.classList.toggle('night',theme==='night');
  const symbol=theme==='night'?'☀':'☾';if($('themeBtn'))$('themeBtn').textContent=symbol;if($('desktopThemeBtn'))$('desktopThemeBtn').textContent=symbol;
  try{setNauticalDepthTheme(theme)}catch{}
}

async function api(method,url,body,{queue=false}={}){
  try{
    const res=await fetch(url,{method,headers:{'content-type':'application/json','accept':'application/json'},body:body==null?undefined:JSON.stringify(body)});
    const data=await res.json().catch(()=>({}));if(!res.ok){const error=new Error(data.error||`HTTP ${res.status}`);error.status=res.status;error.data=data;if(res.status===401&&location.pathname!=='/login')location.replace('/login');throw error}return data;
  }catch(error){
    // Endast riktiga nätverksfel får hamna i offlinekön. HTTP-fel ska visas och inte döljas som "sparat lokalt".
    if(queue&&method!=='GET'&&error?.status==null){
      let pending=loadJson(PENDING_KEY,[]);if(method==='PUT'&&url==='/api/plan'&&body?.date)pending=pending.filter(item=>!(item?.method==='PUT'&&item?.url==='/api/plan'&&item?.body?.date===body.date));pending.push({id:crypto.randomUUID(),method,url,body,queued_at:isoNow()});saveJson(PENDING_KEY,pending);setSync('Offline · sparar lokalt',false);return {ok:true,queued:true};
    }
    throw error;
  }
}

async function flushPending(){if(!navigator.onLine)return;let pending=loadJson(PENDING_KEY,[]);if(!pending.length)return;const remain=[];let conflict=false;for(const item of pending){try{const data=await api(item.method,item.url,item.body);if(item?.url==='/api/plan'&&item?.body?.date===dayPlan.date&&data?.plan){dayPlan.plan=data.plan;const cached=loadJson(PLAN_CACHE_PREFIX+dayPlan.date,null);if(cached)saveJson(PLAN_CACHE_PREFIX+dayPlan.date,{...cached,plan:data.plan})}}catch(error){if(error?.status===409&&item?.url==='/api/plan'){planConflictDates.add(item?.body?.date||dayPlan.date);conflict=true}remain.push(item)}}saveJson(PENDING_KEY,remain);if(conflict)toast('Planen ändrades på en annan enhet · öppna Planera för att välja version',4200);else if(!remain.length)toast('Lokala ändringar synkade')}

async function syncState({quiet=false}={}){
  try{
    await flushPending();const data=await api('GET','/api/state');
    state.traps=Array.isArray(data.traps)?data.traps:[];state.checks=Array.isArray(data.checks)?data.checks:[];state.trips=Array.isArray(data.trips)?data.trips:[];state.user=data.user||'familj';state.serverTime=data.serverTime||null;
    saveJson(CACHE_KEY,state);renderAll();setSync(`Synkad · ${state.user}`);if($('desktopUser'))$('desktopUser').textContent=state.user;if(!quiet)toast('Synkad');
  }catch(error){
    if(error?.status===401)return;const cached=loadJson(CACHE_KEY,null);if(cached){Object.assign(state,cached);renderAll();setSync('Offline · lokal data',false)}else setSync('D1 ej ansluten',false);
    if(!quiet)toast(error.message||'Kunde inte synka');
  }
}

function planUiBusy(){return planDirty||planConflictDates.has(dayPlan.date)||planHasPending()||placementMode!=null||!$('mobilePlanSheet')?.classList.contains('hidden')||!$('planSpotSheet')?.classList.contains('hidden')}
async function syncWorkspace({quiet=false}={}){
  await syncState({quiet:true});
  if(!planUiBusy()) await loadPlan(dayPlan.date,{quiet:true,force:true});
  if(!quiet) toast(navigator.onLine?'Data och plan uppdaterade':'Offline · visar lokala data');
}

function trapLastCheck(trap){const recent=state.checks.find(c=>c.trap_id===trap.id);if(recent)return recent;if(trap?.last_checked_at)return {trap_id:trap.id,checked_at:trap.last_checked_at,lobster_count:Number(trap.last_lobster_count)||0,notes:trap.last_check_notes||''};return null}
function trapAgeClass(trap){if(trap.status==='retrieved')return 'retrieved';if(!trap.last_checked_at)return 'old';const hours=(Date.now()-new Date(trap.last_checked_at).getTime())/36e5;return hours<36?'recent':hours>96?'old':''}
function trapLabel(trap){const s=String(trap.name||'B').trim();return s.length>3?s.slice(0,3):s}
function resolvePlanItem(item){if(item?.kind==='trap'&&item.trap_id){const t=state.traps.find(x=>x.id===item.trap_id);if(t)return {...item,name:t.name,lat:+t.lat,lon:+t.lon,status:t.status,last_checked_at:t.last_checked_at}}return item}

function renderAll(){renderTraps();renderSelected();renderSelectedSpot();renderTrapList();renderDesktopTraps();renderTrips();renderPlan();renderCatch();}

function renderTraps(){
  if(!map)return;const ids=new Set(state.traps.map(t=>t.id));for(const [id,item] of trapMarkers){if(!ids.has(id)){item.marker.remove();trapMarkers.delete(id)}}
  for(const trap of state.traps){
    let item=trapMarkers.get(trap.id);const lngLat=[Number(trap.lon),Number(trap.lat)];if(!lngLat.every(Number.isFinite))continue;
    if(!item){const el=document.createElement('button');el.className='trap-marker';el.type='button';el.setAttribute('aria-label',trap.name||'Bur');el.innerHTML=`<span>${esc(trapLabel(trap))}</span>`;el.addEventListener('click',ev=>{ev.stopPropagation();selectTrap(trap.id)});const marker=new maptilersdk.Marker({element:el,anchor:'bottom'}).setLngLat(lngLat).addTo(map);item={marker,el};trapMarkers.set(trap.id,item)}else item.marker.setLngLat(lngLat);
    item.el.className='trap-marker '+trapAgeClass(trap);item.el.querySelector('span').textContent=trapLabel(trap);const hideInactive=(isDesktop()?desktopFilterActive:filterActiveOnly)&&trap.status!=='active';item.el.style.display=hideInactive?'none':'';
  }
}

function selectTrap(id,{center=false}={}){selectedSpotId=null;selectedTrapId=id;renderSelected();renderSelectedSpot();renderDesktopTraps();const trap=state.traps.find(t=>t.id===id);if(center&&trap&&map)map.easeTo({center:[Number(trap.lon),Number(trap.lat)],zoom:Math.max(map.getZoom(),13.5),duration:500})}
function renderSelected(){
  const card=$('selectedTrapCard'),trap=state.traps.find(t=>t.id===selectedTrapId);if(!card)return;if(!trap){card.classList.add('hidden');return}card.classList.remove('hidden');
  $('selectedName').textContent=trap.name;$('selectedLast').textContent=`Vittjad: ${fmtDate(trap.last_checked_at)}`;const last=trapLastCheck(trap);$('selectedCatch').textContent=last?`${last.lobster_count||0} hummer senast`:'Ingen fångst loggad';if($('skipTrapBtn'))$('skipTrapBtn').classList.toggle('hidden',!roundActive);updateSelectedDistance();
}
function selectPlanSpot(id,{center=false}={}){const spot=dayPlan.items.find(i=>i.id===id&&i.kind==='spot');if(!spot)return;selectedTrapId=null;selectedSpotId=id;renderSelected();renderSelectedSpot();renderDesktopTraps();renderPlanOnMap();if(center&&map)map.easeTo({center:[+spot.lon,+spot.lat],zoom:Math.max(map.getZoom(),14),duration:450})}
function renderSelectedSpot(){const card=$('selectedSpotCard'),spot=dayPlan.items.find(i=>i.id===selectedSpotId&&i.kind==='spot');if(!card)return;if(!spot){card.classList.add('hidden');return}card.classList.remove('hidden');$('selectedSpotName').textContent=spot.name||'Planerad plats';$('selectedSpotPosition').textContent=`${Number(spot.lat).toFixed(5)}, ${Number(spot.lon).toFixed(5)}`;$('selectedSpotNote').textContent=spot.notes||'Ej satt bur ännu';$('skipSpotBtn').classList.toggle('hidden',!roundActive);updateSelectedDistance()}
function updateSelectedDistance(){const trap=state.traps.find(t=>t.id===selectedTrapId);if(trap&&$('selectedDistance')){const d=distanceNm(currentPosition,{lat:+trap.lat,lon:+trap.lon});$('selectedDistance').textContent=Number.isFinite(d)?(d<0.1?`${(d*1852).toFixed(0)} m`:`${d.toFixed(2)} NM`):'—'}const spot=dayPlan.items.find(i=>i.id===selectedSpotId&&i.kind==='spot');if(spot&&$('selectedSpotDistance')){const d=distanceNm(currentPosition,{lat:+spot.lat,lon:+spot.lon});$('selectedSpotDistance').textContent=Number.isFinite(d)?(d<0.1?`${(d*1852).toFixed(0)} m`:`${d.toFixed(2)} NM`):'—'}}

function trapRowHtml(t){const d=distanceNm(currentPosition,{lat:+t.lat,lon:+t.lon}),last=trapLastCheck(t);return `<button class="trap-row ${t.status==='retrieved'?'retrieved':''}" data-trap-id="${esc(t.id)}"><span class="trap-dot">${esc(trapLabel(t))}</span><span><strong>${esc(t.name)}</strong><small>${t.status==='retrieved'?'Upptagen':'Vittjad '+esc(fmtDate(t.last_checked_at))}${last?` · ${Number(last.lobster_count)||0} hummer`:''}</small></span><span class="row-distance">${Number.isFinite(d)?(d<0.1?Math.round(d*1852)+' m':d.toFixed(1)+' NM'):'—'}</span></button>`}
function renderTrapList(){const list=$('trapList');if(!list)return;const traps=state.traps.filter(t=>!filterActiveOnly||t.status==='active');list.innerHTML=traps.length?traps.map(trapRowHtml).join(''):'<div class="empty-state"><strong>Inga burar ännu</strong><span>Sätt första buren från kartan.</span></div>';list.querySelectorAll('[data-trap-id]').forEach(btn=>btn.addEventListener('click',()=>{closeSheets();selectTrap(btn.dataset.trapId,{center:true})}))}

function renderDesktopTraps(){
  const list=$('desktopTrapList');if(!list)return;const q=desktopSearch.trim().toLowerCase();let traps=state.traps.filter(t=>(!desktopFilterActive||t.status==='active')&&(!q||String(t.name).toLowerCase().includes(q)||String(t.notes||'').toLowerCase().includes(q)));
  list.innerHTML=traps.length?traps.map(t=>{const last=trapLastCheck(t);return `<button class="desktop-row ${t.id===selectedTrapId?'selected':''} ${t.status==='retrieved'?'muted-row':''}" data-desktop-trap="${esc(t.id)}"><span class="trap-dot">${esc(trapLabel(t))}</span><span><strong>${esc(t.name)}</strong><small>${t.status==='retrieved'?'Upptagen':`Senast ${esc(fmtDate(t.last_checked_at))}`}${last?` · ${Number(last.lobster_count)||0} hummer`:''}</small></span><span class="row-distance">${esc(t.updated_by||'')}</span></button>`}).join(''):'<div class="empty-state"><strong>Inga träffar</strong><span>Ändra sökning eller filter.</span></div>';
  list.querySelectorAll('[data-desktop-trap]').forEach(btn=>btn.addEventListener('click',()=>selectTrap(btn.dataset.desktopTrap,{center:true})));
}

function openSheet(id){document.querySelectorAll('.sheet').forEach(s=>s.classList.add('hidden'));$('backdrop').classList.remove('hidden');$(id).classList.remove('hidden')}
function closeSheets(){if(pendingSpotConversionId&&$('trapFormSheet')&&!$('trapFormSheet').classList.contains('hidden'))pendingSpotConversionId=null;$('backdrop').classList.add('hidden');document.querySelectorAll('.sheet').forEach(s=>s.classList.add('hidden'))}
async function openNewTrap(){pendingSpotConversionId=null;let pos=currentPosition&&Date.now()-lastPositionAt<15000?currentPosition:null;if(!pos){toast('Hämtar aktuell GPS-position…');try{const fix=await getGpsFix();handlePosition(fix);pos={lat:fix.coords.latitude,lon:fix.coords.longitude}}catch(error){toast(`GPS kunde inte hämtas · ${error.message||'kontrollera platsbehörighet'}`,3800);startGps();return}}openNewTrapAt(pos)}
function openNewTrapAt(pos){$('trapFormEyebrow').textContent='NY BUR';$('trapFormTitle').textContent='Sätt bur';$('trapId').value='';$('trapName').value=nextTrapName();$('trapLat').value=Number(pos.lat).toFixed(6);$('trapLon').value=Number(pos.lon).toFixed(6);$('trapNotes').value='';$('retrieveTrapBtn').classList.add('hidden');openSheet('trapFormSheet');setTimeout(()=>$('trapName').select(),80)}
function openEditTrap(){pendingSpotConversionId=null;const t=state.traps.find(x=>x.id===selectedTrapId);if(!t)return;$('trapFormEyebrow').textContent='ÄNDRA BUR';$('trapFormTitle').textContent=t.name;$('trapId').value=t.id;$('trapName').value=t.name;$('trapLat').value=t.lat;$('trapLon').value=t.lon;$('trapNotes').value=t.notes||'';$('retrieveTrapBtn').classList.toggle('hidden',t.status!=='active');openSheet('trapFormSheet')}
function nextTrapName(){const nums=state.traps.map(t=>String(t.name||'').match(/^B(\d+)$/i)).filter(Boolean).map(m=>+m[1]);return `B${Math.max(0,...nums)+1}`}
async function retrieveTrap(){const trap=state.traps.find(x=>x.id===$('trapId').value.trim());if(!trap)return;trap.status='retrieved';trap.updated_at=isoNow();await api('DELETE',`/api/traps/${encodeURIComponent(trap.id)}`,null,{queue:true});if(roundActive)roundVisited.add(`trap:${trap.id}`);saveJson(CACHE_KEY,state);renderAll();closeSheets();toast(`${trap.name} markerad som upptagen`);if(roundActive)setTimeout(gotoNextRoundStop,300);setTimeout(()=>syncWorkspace({quiet:true}),500)}
function openCheck(){const t=state.traps.find(x=>x.id===selectedTrapId);if(!t)return;$('checkTrapName').textContent=t.name;$('lobsterCount').value='0';$('lobsterCount').textContent='0';$('releasedCount').value='0';$('checkNotes').value='';openSheet('checkSheet')}
async function saveTrap(ev){ev.preventDefault();const id=$('trapId').value.trim(),conversionSpotId=!id?pendingSpotConversionId:null,existing=id?state.traps.find(x=>x.id===id):null,body={id:id||crypto.randomUUID(),name:$('trapName').value.trim(),lat:Number($('trapLat').value),lon:Number($('trapLon').value),notes:$('trapNotes').value.trim(),set_at:existing?.set_at||isoNow()};if(!body.name||!Number.isFinite(body.lat)||!Number.isFinite(body.lon)){toast('Kontrollera namn och position');return}if(id){const t=state.traps.find(x=>x.id===id);Object.assign(t,body,{updated_at:isoNow()});await api('PATCH',`/api/traps/${encodeURIComponent(id)}`,body,{queue:true});selectedTrapId=id}else{state.traps.unshift({...body,status:'active',last_checked_at:null,created_at:isoNow(),updated_at:isoNow(),updated_by:state.user});await api('POST','/api/traps',body,{queue:true});selectedTrapId=body.id}if(conversionSpotId){const index=dayPlan.items.findIndex(i=>i.id===conversionSpotId&&i.kind==='spot');if(index>=0){dayPlan.items[index]={id:conversionSpotId,kind:'trap',trap_id:body.id,name:body.name,lat:body.lat,lon:body.lon,notes:''};roundVisited.add(`spot:${conversionSpotId}`);roundVisited.add(`trap:${body.id}`);selectedSpotId=null;pendingSpotConversionId=null;markPlanDirty({autosave:false});await savePlan({quiet:true})}}pendingSpotConversionId=null;saveJson(CACHE_KEY,state);renderAll();closeSheets();toast(conversionSpotId?'Bur satt · planpunkten är ersatt':id?'Bur uppdaterad':'Bur satt');if(roundActive&&conversionSpotId)setTimeout(gotoNextRoundStop,450);setTimeout(()=>syncWorkspace({quiet:true}),500)}
async function saveCheck(ev){ev.preventDefault();const trap=state.traps.find(x=>x.id===selectedTrapId);if(!trap)return;const body={id:crypto.randomUUID(),trap_id:trap.id,checked_at:isoNow(),lobster_count:Number($('lobsterCount').value||$('lobsterCount').textContent||0),released_count:Number($('releasedCount').value||0),notes:$('checkNotes').value.trim(),lat:currentPosition?.lat??null,lon:currentPosition?.lon??null};state.checks.unshift({...body,actor:state.user,trap_name:trap.name});trap.last_checked_at=body.checked_at;trap.updated_at=body.checked_at;await api('POST','/api/checks',body,{queue:true});roundVisited.add(`trap:${trap.id}`);saveJson(CACHE_KEY,state);renderAll();closeSheets();toast(`${trap.name} vittjad · ${body.lobster_count} hummer`);if(roundActive)setTimeout(gotoNextRoundStop,450);setTimeout(()=>{syncWorkspace({quiet:true});loadHeatmap({quiet:true})},600)}

function setNavigationTarget(name,target){const d=distanceNm(currentPosition,target),b=bearingDeg(currentPosition,target);if(!currentPosition){$('navBanner').classList.add('hidden');setNavLine(null);return}$('navBanner').classList.remove('hidden');$('navTargetName').textContent=name;$('navDistance').textContent=d<0.1?`${Math.round(d*1852)} m`:`${d.toFixed(2)} NM`;$('navBearing').textContent=Number.isFinite(b)?`${Math.round(b)}°`:'—';setNavLine(target)}
function updateNavigation(){if(!navigationTarget||!currentPosition){if(navigationTarget)$('navBanner').classList.add('hidden');if(!navigationTarget)setNavLine(null);return}let target=navigationTarget;if(target.kind==='trap'){const trap=state.traps.find(t=>t.id===target.id);if(!trap){stopNavigation();return}target={...target,name:trap.name,lat:+trap.lat,lon:+trap.lon};navigationTarget=target}else if(target.kind==='spot'){const spot=dayPlan.items.find(i=>i.id===target.id&&i.kind==='spot');if(!spot){stopNavigation();return}target={...target,name:spot.name,lat:+spot.lat,lon:+spot.lon};navigationTarget=target}setNavigationTarget(target.name,{lat:+target.lat,lon:+target.lon});if($('navigateTrapBtn'))$('navigateTrapBtn').textContent=target.kind==='trap'&&target.id===selectedTrapId?'Navigerar':'Navigera';if($('navigateSpotBtn'))$('navigateSpotBtn').textContent=target.kind==='spot'&&target.id===selectedSpotId?'Navigerar':'Navigera'}
function startNavigation(id=selectedTrapId){if(!id)return;const t=state.traps.find(x=>x.id===id);if(!t)return;navigationTarget={kind:'trap',id:t.id,name:t.name,lat:+t.lat,lon:+t.lon};updateNavigation();map?.easeTo({center:[+t.lon,+t.lat],zoom:Math.max(map.getZoom(),13.5),duration:500})}
function startSpotNavigation(id=selectedSpotId){const spot=dayPlan.items.find(i=>i.id===id&&i.kind==='spot');if(!spot)return;navigationTarget={kind:'spot',id:spot.id,name:spot.name,lat:+spot.lat,lon:+spot.lon};updateNavigation();map?.easeTo({center:[+spot.lon,+spot.lat],zoom:Math.max(map.getZoom(),13.8),duration:500})}
function stopNavigation(){navigationTarget=null;$('navBanner').classList.add('hidden');if($('navigateTrapBtn'))$('navigateTrapBtn').textContent='Navigera';if($('navigateSpotBtn'))$('navigateSpotBtn').textContent='Navigera';setNavLine(null)}
function setNavLine(target){if(!map||!map.getSource('nav-line'))return;map.getSource('nav-line').setData({type:'FeatureCollection',features:target&&currentPosition?[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[[currentPosition.lon,currentPosition.lat],[target.lon,target.lat]]}}]:[]})}

function planStopKey(item){return item?.kind==='spot'?`spot:${item.id}`:item?.trap_id?`trap:${item.trap_id}`:null}
function resolveRoundStop(key){if(key?.startsWith('spot:')){const id=key.slice(5),item=dayPlan.items.find(i=>i.id===id&&i.kind==='spot');return item?{kind:'spot',key,item}:null}if(key?.startsWith('trap:')){const id=key.slice(5),trap=state.traps.find(t=>t.id===id&&t.status==='active');return trap?{kind:'trap',key,trap}:null}return null}
async function toggleRound(){
  if(roundActive){roundActive=false;roundSequence=[];stopNavigation();resetRoundButton();renderSelected();renderSelectedSpot();toast('Hummerrunda avslutad');return}
  if(planDirty) await savePlan({quiet:true});
  await ensureTodayPlan();
  if(planConflictDates.has(localDateKey())){toast('Dagens plan har en synkkonflikt · öppna Planera och välj version först',4800);return}
  roundActive=true;roundVisited.clear();$('roundBtn').classList.add('running');
  if(!currentPosition&&!isDesktop()) startGps();
  buildRoundSequence();
  if(!roundSequence.length&&!currentPosition&&!isDesktop()){
    try{const fix=await getGpsFix();handlePosition(fix)}catch{toast('Ingen plan och ingen GPS-fix · kan inte välja närmaste bur',4200);roundActive=false;resetRoundButton();renderSelected();renderSelectedSpot();return}
  }
  toast(roundSequence.length?'Planerad hummerrunda startad':'Hummerrunda startad');gotoNextRoundStop();
}
function buildRoundSequence(){const source=dayPlan.date===localDateKey()?dayPlan.items:[],seen=new Set();roundSequence=source.map(resolvePlanItem).filter(i=>i.kind==='spot'||(i.kind==='trap'&&i.trap_id&&i.status==='active')).map(planStopKey).filter(key=>key&&!seen.has(key)&&seen.add(key));renderSelected();renderSelectedSpot();renderPlan()}
function resetRoundButton(){$('roundBtn').innerHTML='<span>↝</span>Runda';$('roundBtn').classList.remove('running')}
function finishRound(){roundActive=false;roundSequence=[];resetRoundButton();stopNavigation();selectedSpotId=null;selectedTrapId=null;renderSelected();renderSelectedSpot();renderPlan();toast('Rundan klar · alla planerade stopp hanterade',3500)}
function gotoNextRoundStop(){if(!roundActive)return;if(roundSequence.length){const remaining=roundSequence.filter(key=>!roundVisited.has(key)).map(resolveRoundStop).filter(Boolean);if(!remaining.length){finishRound();return}const target=remaining[0];if(target.kind==='trap'){selectTrap(target.trap.id);startNavigation(target.trap.id)}else{selectPlanSpot(target.item.id);startSpotNavigation(target.item.id)}$('roundBtn').innerHTML=`<span>↝</span>${remaining.length} kvar`;renderSelected();renderSelectedSpot();renderPlan();return}const options=state.traps.filter(t=>t.status==='active'&&!roundVisited.has(`trap:${t.id}`)).sort((a,b)=>distanceNm(currentPosition,{lat:+a.lat,lon:+a.lon})-distanceNm(currentPosition,{lat:+b.lat,lon:+b.lon}));if(!options.length){finishRound();return}const target=options[0];selectTrap(target.id);startNavigation(target.id);$('roundBtn').innerHTML=`<span>↝</span>${options.length} kvar`;renderSelected()}
function skipSelectedSpot(){const spot=dayPlan.items.find(i=>i.id===selectedSpotId&&i.kind==='spot');if(!spot)return;roundVisited.add(`spot:${spot.id}`);if(navigationTarget?.kind==='spot'&&navigationTarget.id===spot.id)stopNavigation();selectedSpotId=null;renderSelectedSpot();renderPlan();toast(`${spot.name} hoppades över`);if(roundActive)setTimeout(gotoNextRoundStop,250)}
function skipSelectedTrap(){const trap=state.traps.find(i=>i.id===selectedTrapId);if(!trap)return;roundVisited.add(`trap:${trap.id}`);if(navigationTarget?.kind==='trap'&&navigationTarget.id===trap.id)stopNavigation();selectedTrapId=null;renderSelected();renderPlan();toast(`${trap.name} hoppades över`);if(roundActive)setTimeout(gotoNextRoundStop,250)}

function ensureTrackingLayers(){
  if(!map.getSource('track'))map.addSource('track',{type:'geojson',data:{type:'FeatureCollection',features:[]}});if(!map.getLayer('track-line'))map.addLayer({id:'track-line',type:'line',source:'track',paint:{'line-color':'#f2c76d','line-width':['interpolate',['linear'],['zoom'],8,2,15,4],'line-opacity':.94},layout:{'line-join':'round','line-cap':'round'}});
  if(!map.getSource('history-track'))map.addSource('history-track',{type:'geojson',data:{type:'FeatureCollection',features:[]}});if(!map.getLayer('history-track-line'))map.addLayer({id:'history-track-line',type:'line',source:'history-track',paint:{'line-color':'#77c7b2','line-width':['interpolate',['linear'],['zoom'],8,1.5,15,3],'line-opacity':.72},layout:{'line-join':'round','line-cap':'round'}});
  if(!map.getSource('nav-line'))map.addSource('nav-line',{type:'geojson',data:{type:'FeatureCollection',features:[]}});if(!map.getLayer('nav-line-layer'))map.addLayer({id:'nav-line-layer',type:'line',source:'nav-line',paint:{'line-color':'#f6db8c','line-width':2,'line-dasharray':[2,2],'line-opacity':.9}});
}
function renderTrack(){if(!map||!map.getSource('track'))return;map.getSource('track').setData({type:'FeatureCollection',features:tripPoints.length>1?[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:tripPoints.map(p=>[p.lon,p.lat])}}]:[]})}
async function showHistoryTrack(id){if(!id||!map)return;try{const data=await api('GET',`/api/trips/${encodeURIComponent(id)}/track`),points=Array.isArray(data.points)?data.points:[];historyTripId=id;const coords=points.map(p=>[+p.lon,+p.lat]).filter(p=>p.every(Number.isFinite));map.getSource('history-track')?.setData({type:'FeatureCollection',features:coords.length>1?[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:coords}}]:[]});renderTrips();if(coords.length){const bounds=coords.reduce((b,c)=>b.extend(c),new maptilersdk.LngLatBounds(coords[0],coords[0]));map.fitBounds(bounds,{padding:isDesktop()?70:35,maxZoom:14,duration:600})}}catch(error){toast(error.message||'Kunde inte hämta spåret')}}
function clearHistoryTrack(){historyTripId=null;map?.getSource('history-track')?.setData({type:'FeatureCollection',features:[]});renderTrips()}

function ensurePlanLayer(){if(!map.getSource('plan-route'))map.addSource('plan-route',{type:'geojson',data:{type:'FeatureCollection',features:[]}});if(!map.getLayer('plan-route-line'))map.addLayer({id:'plan-route-line',type:'line',source:'plan-route',paint:{'line-color':'#e4b75f','line-width':['interpolate',['linear'],['zoom'],8,1.2,15,2.5],'line-dasharray':[3,2],'line-opacity':.72},layout:{'line-join':'round','line-cap':'round'}})}
function renderPlanOnMap(){if(!map||!map.getSource('plan-route'))return;for(const item of planMarkers.values())item.remove();planMarkers.clear();const resolved=dayPlan.items.map(resolvePlanItem).filter(i=>Number.isFinite(+i.lat)&&Number.isFinite(+i.lon));const coords=resolved.map(i=>[+i.lon,+i.lat]);map.getSource('plan-route').setData({type:'FeatureCollection',features:coords.length>1?[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:coords}}]:[]});resolved.forEach((item,index)=>{if(item.kind!=='spot')return;const el=document.createElement('button');el.className='plan-marker';if(item.id===selectedSpotId)el.classList.add('selected');if(roundActive&&navigationTarget?.kind==='spot'&&navigationTarget.id===item.id)el.classList.add('round-target');el.type='button';el.textContent=String(index+1);el.title=item.name;el.addEventListener('click',ev=>{ev.stopPropagation();selectPlanSpot(item.id,{center:true})});const marker=new maptilersdk.Marker({element:el,anchor:'center'}).setLngLat([+item.lon,+item.lat]).addTo(map);planMarkers.set(item.id,marker)})}
function planDistance(){const items=dayPlan.items.map(resolvePlanItem).filter(i=>Number.isFinite(+i.lat)&&Number.isFinite(+i.lon));let total=0;for(let i=1;i<items.length;i++)total+=distanceNm({lat:+items[i-1].lat,lon:+items[i-1].lon},{lat:+items[i].lat,lon:+items[i].lon});return total}
function planHasPending(date=dayPlan.date){return loadJson(PENDING_KEY,[]).some(item=>item?.url==='/api/plan'&&item?.method==='PUT'&&item?.body?.date===date)}
function discardPendingPlan(date){const pending=loadJson(PENDING_KEY,[]).filter(item=>!(item?.url==='/api/plan'&&item?.method==='PUT'&&item?.body?.date===date));saveJson(PENDING_KEY,pending)}
function planItemHtml(raw,index,all){const i=resolvePlanItem(raw),key=planStopKey(i),done=roundActive&&roundVisited.has(key),trapExists=i.kind!=='trap'||state.traps.some(t=>t.id===i.trap_id),kindText=i.kind==='spot'?'Planerad plats':!trapExists?'Bur · saknas':i.status==='retrieved'?'Bur · upptagen':`Bur · ${esc(fmtDate(i.last_checked_at))}`,open=i.kind==='spot'?`data-plan-open-spot="${esc(raw.id)}"`:`data-plan-open-trap="${esc(i.trap_id||'')}"`;return `<div class="plan-row ${done?'done':''}"><span class="plan-index">${done?'✓':index+1}</span><button class="plan-main" ${open}><strong>${esc(i.name)}</strong><small>${kindText}</small></button><span class="plan-row-actions"><button data-plan-up="${esc(raw.id)}" aria-label="Flytta upp" ${index===0?'disabled':''}>↑</button><button data-plan-down="${esc(raw.id)}" aria-label="Flytta ned" ${index===all.length-1?'disabled':''}>↓</button><button data-plan-remove="${esc(raw.id)}" aria-label="Ta bort">×</button></span></div>`}
function planPickerHtml(available){return available.length?available.map(t=>`<button class="desktop-row" data-plan-add="${esc(t.id)}"><span class="trap-dot">${esc(trapLabel(t))}</span><span><strong>${esc(t.name)}</strong><small>${esc(fmtDate(t.last_checked_at))}</small></span><span class="plus-sign">＋</span></button>`).join(''):'<div class="empty-state"><strong>Alla aktiva burar är med</strong></div>'}
function bindPlanControls(root){if(!root)return;root.querySelectorAll('[data-plan-up]').forEach(b=>b.addEventListener('click',()=>movePlanItem(b.dataset.planUp,-1)));root.querySelectorAll('[data-plan-down]').forEach(b=>b.addEventListener('click',()=>movePlanItem(b.dataset.planDown,1)));root.querySelectorAll('[data-plan-remove]').forEach(b=>b.addEventListener('click',()=>removePlanItem(b.dataset.planRemove)));root.querySelectorAll('[data-plan-add]').forEach(b=>b.addEventListener('click',()=>addTrapToPlan(b.dataset.planAdd)));root.querySelectorAll('[data-plan-open-spot]').forEach(b=>b.addEventListener('click',()=>{closeSheets();selectPlanSpot(b.dataset.planOpenSpot,{center:true})}));root.querySelectorAll('[data-plan-open-trap]').forEach(b=>b.addEventListener('click',()=>{closeSheets();selectTrap(b.dataset.planOpenTrap,{center:true})}))}
function renderPlan(){
  for(const id of ['planDate','mobilePlanDate'])if($(id))$(id).value=dayPlan.date;
  const distance=`${planDistance().toFixed(1)} NM`,trapCount=String(dayPlan.items.filter(i=>i.kind==='trap').length),stopCount=String(dayPlan.items.length);
  for(const id of ['planStopCount','mobilePlanStopCount'])if($(id))$(id).textContent=stopCount;for(const id of ['planTrapCount','mobilePlanTrapCount'])if($(id))$(id).textContent=trapCount;for(const id of ['planDistance','mobilePlanDistance'])if($(id))$(id).textContent=distance;
  const html=dayPlan.items.length?dayPlan.items.map(planItemHtml).join(''):'<div class="empty-state"><strong>Ingen plan ännu</strong><span>Lägg till burar eller en planerad plats.</span></div>';
  const chosen=new Set(dayPlan.items.filter(i=>i.trap_id).map(i=>i.trap_id)),available=state.traps.filter(t=>t.status==='active'&&!chosen.has(t.id)),pickerHtml=planPickerHtml(available);
  for(const id of ['planItems','mobilePlanItems'])if($(id)){$(id).innerHTML=html;bindPlanControls($(id))}for(const id of ['planTrapPicker','mobilePlanTrapPicker'])if($(id)){$(id).innerHTML=pickerHtml;bindPlanControls($(id))}
  const pending=planHasPending(),conflict=planConflictDates.has(dayPlan.date),saveText=conflict?'Konflikt':planSaveInFlight?'Sparar…':planDirty?'Spara *':pending?'Sparad lokalt':'Sparad';
  if($('savePlanBtn'))$('savePlanBtn').textContent=conflict?'Plan-konflikt':planSaveInFlight?'Sparar…':planDirty?'Spara plan *':pending?'Sparad lokalt':'Spara plan';
  if($('mobileSavePlanBtn')){$('mobileSavePlanBtn').textContent=saveText;$('mobileSavePlanBtn').classList.toggle('pending',planDirty||planSaveInFlight);$('mobileSavePlanBtn').classList.toggle('offline',pending);$('mobileSavePlanBtn').classList.toggle('error',conflict)}
  if($('mobilePlanStatus')){$('mobilePlanStatus').textContent=conflict?'Planen har ändrats på en annan enhet. Hämta om för serverns version eller tryck Konflikt för att skriva över med den här.':pending?'Planen är sparad på telefonen och skickas till Cloudflare när nätet är tillbaka.':planDirty||planSaveInFlight?'Ändringar sparas automatiskt…':planLastSyncedAt?`Samma dagsplan används på mobil och dator · senast hämtad ${fmtClock(planLastSyncedAt)}`:'Samma dagsplan används på mobil och dator.'}
  if($('mobileStartRoundBtn'))$('mobileStartRoundBtn').textContent=roundActive?'↝ Tillbaka till rundan':dayPlan.date===localDateKey()?'↝ Starta rundan':'↝ Öppna dagens runda';
  renderPlanOnMap();renderSelectedSpot();
}
function markPlanDirty({autosave=true}={}){planRevision++;planDirty=true;if(roundActive)buildRoundSequence();renderPlan();clearTimeout(planSaveTimer);if(autosave)planSaveTimer=setTimeout(()=>savePlan({quiet:true}),700)}
function addTrapToPlan(id){const t=state.traps.find(x=>x.id===id);if(!t||dayPlan.items.some(i=>i.trap_id===id))return;dayPlan.items.push({id:crypto.randomUUID(),kind:'trap',trap_id:t.id,name:t.name,lat:+t.lat,lon:+t.lon,notes:''});markPlanDirty();toast(`${t.name} tillagd i planen`)}
function movePlanItem(id,delta){const i=dayPlan.items.findIndex(x=>x.id===id),j=i+delta;if(i<0||j<0||j>=dayPlan.items.length)return;[dayPlan.items[i],dayPlan.items[j]]=[dayPlan.items[j],dayPlan.items[i]];markPlanDirty()}
function removePlanItem(id){const item=dayPlan.items.find(x=>x.id===id);if(!item)return;dayPlan.items=dayPlan.items.filter(x=>x.id!==id);if(selectedSpotId===id)selectedSpotId=null;if(navigationTarget?.kind==='spot'&&navigationTarget.id===id)stopNavigation();markPlanDirty();toast(`${item.name||'Stopp'} borttaget`)}
function addAllTrapsToPlan(){const chosen=new Set(dayPlan.items.filter(i=>i.trap_id).map(i=>i.trap_id));let added=0;state.traps.filter(t=>t.status==='active'&&!chosen.has(t.id)).forEach(t=>{dayPlan.items.push({id:crypto.randomUUID(),kind:'trap',trap_id:t.id,name:t.name,lat:+t.lat,lon:+t.lon,notes:''});added++});if(added){markPlanDirty();toast(`${added} bur${added===1?'':'ar'} tillagd${added===1?'':'a'}`)}else toast('Alla aktiva burar är redan med')}
function fitPlanOnMap(){const coords=dayPlan.items.map(resolvePlanItem).map(i=>[+i.lon,+i.lat]).filter(c=>c.every(Number.isFinite));if(!coords.length){toast('Planen har inga stopp att visa');return}if(!isDesktop())closeSheets();if(coords.length===1){map?.easeTo({center:coords[0],zoom:Math.max(map.getZoom(),14),duration:500});return}const bounds=coords.reduce((b,c)=>b.extend(c),new maptilersdk.LngLatBounds(coords[0],coords[0]));map?.fitBounds(bounds,{padding:isDesktop()?70:45,maxZoom:14.5,duration:600})}
function beginPlacement(kind,{returnTo=null}={}){placementMode=kind;placementReturn=returnTo;document.body.classList.add('placement-mode');if(!isDesktop())closeSheets();const moving=String(kind).startsWith('move-spot:'),text=moving?'Tryck på den nya positionen på sjökortet':kind==='spot'?'Tryck på sjökortet där den planerade platsen ska ligga':'Tryck på sjökortet där buren ska placeras';if($('placementEyebrow'))$('placementEyebrow').textContent=moving?'FLYTTA PLATS':kind==='spot'?'PLANERA':'SÄTT BUR';if($('placementText'))$('placementText').textContent=text;$('placementBanner')?.classList.remove('hidden');toast(text,4200)}
function endPlacement(){const ret=placementReturn;placementMode=null;placementReturn=null;document.body.classList.remove('placement-mode');$('placementBanner')?.classList.add('hidden');return ret}
function cancelPlacement(){const ret=endPlacement();if(ret==='mobile-plan')openMobilePlan({refresh:false});else if(ret==='spot-editor')openSpotEditor();toast('Kartplacering avbruten')}
function nextPlannedSpotName(){const nums=dayPlan.items.map(i=>String(i.name||'').match(/^Planerad plats (\d+)$/i)).filter(Boolean).map(m=>+m[1]);return `Planerad plats ${Math.max(0,...nums)+1}`}
function addPlannedSpot(lngLat){const spot={id:crypto.randomUUID(),kind:'spot',trap_id:null,name:nextPlannedSpotName(),lat:+lngLat.lat,lon:+lngLat.lng,notes:''};dayPlan.items.push(spot);const ret=endPlacement();selectedSpotId=spot.id;markPlanDirty();if(ret==='mobile-plan')openMobilePlan({refresh:false});else selectPlanSpot(spot.id,{center:false});toast('Planerad plats tillagd')}
function getGpsFix(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GPS stöds inte av den här webbläsaren'));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,maximumAge:3000,timeout:15000})})}
async function addPlannedSpotAtCurrentPosition(){let pos=currentPosition&&Date.now()-lastPositionAt<15000?currentPosition:null;if(!pos){toast('Hämtar GPS-position…');try{const fix=await getGpsFix();handlePosition(fix);pos={lat:fix.coords.latitude,lon:fix.coords.longitude}}catch(error){toast(`GPS kunde inte hämtas · ${error.message||'kontrollera platsbehörighet'}`,3800);return}}const spot={id:crypto.randomUUID(),kind:'spot',trap_id:null,name:nextPlannedSpotName(),lat:+pos.lat,lon:+pos.lon,notes:''};dayPlan.items.push(spot);selectedSpotId=spot.id;markPlanDirty();toast('Din position lades till i planen')}
async function openMobilePlan({refresh=true}={}){renderPlan();openSheet('mobilePlanSheet');if(refresh&&navigator.onLine&&!planDirty){await loadPlan(dayPlan.date,{quiet:true,force:true});renderPlan()}}
async function refreshCurrentPlan(){if(!navigator.onLine){toast('Ingen anslutning · kan inte hämta om planen från Cloudflare');return}const conflict=planConflictDates.has(dayPlan.date);if(planDirty||conflict||planHasPending()){const ok=confirm('Hämta planen från Cloudflare och ersätt lokala/osynkade ändringar för detta datum?');if(!ok)return;discardPendingPlan(dayPlan.date);planDirty=false;planConflictDates.delete(dayPlan.date)}await loadPlan(dayPlan.date,{quiet:true,force:true});toast(navigator.onLine?'Planen hämtad från Cloudflare':'Visar lokalt sparad plan')}
async function startRoundFromPlan(){closeSheets();if(roundActive){gotoNextRoundStop();return}if(dayPlan.date!==localDateKey()){if(planDirty)await savePlan({quiet:true});await loadPlan(localDateKey(),{quiet:true});toast('Dagens plan öppnad')}await toggleRound()}
function openSpotEditor(){const spot=dayPlan.items.find(i=>i.id===selectedSpotId&&i.kind==='spot');if(!spot)return;$('planSpotId').value=spot.id;$('planSpotTitle').textContent=spot.name||'Planerad plats';$('planSpotName').value=spot.name||'';$('planSpotLat').value=Number(spot.lat).toFixed(6);$('planSpotLon').value=Number(spot.lon).toFixed(6);$('planSpotNotes').value=spot.notes||'';openSheet('planSpotSheet')}
function saveSpotEdit(ev){ev.preventDefault();const id=$('planSpotId').value,spot=dayPlan.items.find(i=>i.id===id&&i.kind==='spot'),lat=Number($('planSpotLat').value),lon=Number($('planSpotLon').value),name=$('planSpotName').value.trim();if(!spot||!name||!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180){toast('Kontrollera namn och position');return}Object.assign(spot,{name,lat,lon,notes:$('planSpotNotes').value.trim()});selectedSpotId=id;markPlanDirty();closeSheets();renderSelectedSpot();updateNavigation();toast('Planerad plats uppdaterad')}
function deleteSelectedSpot(){const id=$('planSpotId').value||selectedSpotId;if(!id)return;closeSheets();removePlanItem(id)}
function moveSelectedSpotOnMap(){const id=$('planSpotId').value||selectedSpotId;if(!id)return;beginPlacement(`move-spot:${id}`,{returnTo:isDesktop()?'desktop-plan':'spot-editor'})}
async function useGpsForSpot(){let pos=currentPosition&&Date.now()-lastPositionAt<15000?currentPosition:null;if(!pos){toast('Hämtar GPS-position…');try{const fix=await getGpsFix();handlePosition(fix);pos={lat:fix.coords.latitude,lon:fix.coords.longitude}}catch(error){toast(`GPS kunde inte hämtas · ${error.message||'kontrollera platsbehörighet'}`,3800);return}}$('planSpotLat').value=Number(pos.lat).toFixed(6);$('planSpotLon').value=Number(pos.lon).toFixed(6);toast('GPS-position ifylld')}
function openTrapFromSelectedSpot(){const spot=dayPlan.items.find(i=>i.id===selectedSpotId&&i.kind==='spot');if(!spot)return;pendingSpotConversionId=spot.id;const gpsGood=currentPosition&&Date.now()-lastPositionAt<15000&&(!Number.isFinite(currentAccuracy)||currentAccuracy<=40),pos=gpsGood?currentPosition:{lat:+spot.lat,lon:+spot.lon};openNewTrapAt(pos);$('trapFormEyebrow').textContent='PLANERAD PLATS → BUR';$('trapFormTitle').textContent=spot.name||'Sätt bur';$('trapNotes').value=spot.notes||'';if(currentPosition&&!gpsGood)toast('GPS-noggrannheten är låg · planerad position används',3600)}
async function loadPlan(date=localDateKey(),{quiet=false,force=false}={}){if(!force&&date===dayPlan.date&&planDirty){renderPlan();return false}if(!force&&(planConflictDates.has(date)||planHasPending(date))){clearTimeout(planSaveTimer);const cached=loadJson(PLAN_CACHE_PREFIX+date,null);dayPlan=cached||{date,plan:null,items:[]};dayPlan.date=date;planDirty=false;planRevision++;renderPlan();return false}clearTimeout(planSaveTimer);dayPlan.date=date;try{const data=await api('GET',`/api/plan?date=${encodeURIComponent(date)}`);dayPlan={date,plan:data.plan||null,items:Array.isArray(data.items)?data.items:[]};saveJson(PLAN_CACHE_PREFIX+date,dayPlan);planDirty=false;planConflictDates.delete(date);planRevision++;planLastSyncedAt=Date.now();if(selectedSpotId&&!dayPlan.items.some(i=>i.id===selectedSpotId&&i.kind==='spot'))selectedSpotId=null;renderPlan();if(!quiet)toast('Plan hämtad');return true}catch(error){if(error?.status===401)return false;const cached=loadJson(PLAN_CACHE_PREFIX+date,null);if(cached){dayPlan=cached;planDirty=false;planRevision++;renderPlan();if(!quiet)toast('Visar lokalt sparad plan')}else{dayPlan={date,plan:null,items:[]};planDirty=false;planRevision++;renderPlan();if(!quiet)toast('Kunde inte hämta plan')}return false}}
async function changePlanDate(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(date||'')))return;if(planDirty)await savePlan({quiet:true});await loadPlan(date)}
async function ensureTodayPlan(){const today=localDateKey();if(dayPlan.date!==today){if(planDirty)await savePlan({quiet:true});await loadPlan(today,{quiet:true});return}if(!dayPlan.plan&&!dayPlan.items.length&&!planDirty&&!planHasPending(today))await loadPlan(today,{quiet:true})}
async function savePlan({quiet=false,forceOverwrite=false}={}){
  clearTimeout(planSaveTimer);
  const conflict=planConflictDates.has(dayPlan.date);
  if(conflict&&!forceOverwrite){
    if(quiet)return;
    const ok=confirm('Planen har ändrats på en annan enhet. Vill du skriva över Cloudflare-planen med den här versionen?');
    if(!ok)return;
    forceOverwrite=true;
  }
  if(planSaveInFlight){planSaveTimer=setTimeout(()=>savePlan({quiet:true}),350);return}
  const saveRevision=planRevision,saveDate=dayPlan.date;
  if(forceOverwrite){discardPendingPlan(saveDate);planConflictDates.delete(saveDate)}
  const body={date:saveDate,name:`Hummerrunda ${saveDate}`,base_known:true,base_updated_at:dayPlan.plan?.updated_at||null,force:Boolean(forceOverwrite),items:dayPlan.items.map((raw,index)=>{const i=resolvePlanItem(raw);return {id:raw.id,kind:raw.kind,trap_id:raw.trap_id||null,name:i.name,lat:+i.lat,lon:+i.lon,notes:raw.notes||'',seq:index}})};
  saveJson(PLAN_CACHE_PREFIX+saveDate,{...dayPlan,date:saveDate,items:body.items});planSaveInFlight=true;renderPlan();
  try{
    const data=await api('PUT','/api/plan',body,{queue:true}),stillCurrent=saveRevision===planRevision&&saveDate===dayPlan.date;
    if(!data.queued&&stillCurrent){dayPlan={date:saveDate,plan:data.plan||dayPlan.plan,items:Array.isArray(data.items)?data.items:dayPlan.items};planLastSyncedAt=Date.now();planConflictDates.delete(saveDate)}
    if(stillCurrent)planDirty=false;
    if(!quiet)toast(data.queued?'Plan sparad lokalt':'Plan sparad');
  }catch(error){
    if(saveRevision===planRevision&&saveDate===dayPlan.date)planDirty=true;
    if(error?.status===409){planConflictDates.add(saveDate);toast('Planen ändrades på en annan enhet · välj Hämta om eller Konflikt',4800)}else if(!quiet)toast(error.message||'Kunde inte spara plan');
  }finally{
    planSaveInFlight=false;renderPlan();
    // Nyare redigeringar som skedde medan en save pågick får en ny autosave. Serverfel loopas inte var 700 ms.
    if(planDirty&&planRevision!==saveRevision&&!planConflictDates.has(saveDate)){clearTimeout(planSaveTimer);planSaveTimer=setTimeout(()=>savePlan({quiet:true}),700)}
  }
}

function ensureHeatmapLayer(){if(!map.getSource('catch-heat'))map.addSource('catch-heat',{type:'geojson',data:{type:'FeatureCollection',features:[]}});if(!map.getLayer('catch-heat-layer'))map.addLayer({id:'catch-heat-layer',type:'heatmap',source:'catch-heat',maxzoom:17,layout:{visibility:'none'},paint:{'heatmap-weight':['interpolate',['linear'],['get','weight'],0,0,1,1],'heatmap-intensity':['interpolate',['linear'],['zoom'],7,.65,12,1,15,1.35],'heatmap-radius':['interpolate',['linear'],['zoom'],7,8,10,15,12,26,14,45,16,70],'heatmap-color':['interpolate',['linear'],['heatmap-density'],0,'rgba(255,249,220,0)',.08,'rgba(255,249,220,.36)',.28,'rgba(247,220,151,.56)',.48,'rgba(239,181,99,.66)',.7,'rgba(222,111,67,.76)',1,'rgba(184,45,42,.88)'],'heatmap-opacity':['interpolate',['linear'],['zoom'],7,.62,13,.72,17,.48]}})}
function updateHeatmapSource(){if(!map||!map.getSource('catch-heat'))return;const features=(heatData.points||[]).map(p=>({type:'Feature',properties:{weight:clamp(Number(p.weight)||0,0,1),avg:Number(p.avg_catch)||0,checks:Number(p.check_count)||0,lobsters:Number(p.lobster_count)||0},geometry:{type:'Point',coordinates:[+p.lon,+p.lat]}})).filter(f=>f.geometry.coordinates.every(Number.isFinite));map.getSource('catch-heat').setData({type:'FeatureCollection',features});map.setLayoutProperty('catch-heat-layer','visibility',heatmapVisible?'visible':'none');document.body.classList.toggle('heatmap-on',heatmapVisible)}
async function loadHeatmap({quiet=false}={}){try{const data=await api('GET','/api/heatmap');heatData={points:Array.isArray(data.points)?data.points:[],totals:data.totals||{checks:0,lobsters:0,average:0}};saveJson(HEAT_CACHE_KEY,heatData);updateHeatmapSource();renderCatch();if(!quiet)toast('Fångstdata uppdaterad')}catch(error){heatData=loadJson(HEAT_CACHE_KEY,heatData);updateHeatmapSource();renderCatch();if(!quiet)toast('Visar cachad fångstdata')}}
function toggleHeatmap(){heatmapVisible=!heatmapVisible;updateHeatmapSource();if(heatmapVisible&&!heatData.points?.length)loadHeatmap();else renderCatch()}
function renderCatch(){if($('heatChecks'))$('heatChecks').textContent=String(heatData.totals?.checks||0);if($('heatLobsters'))$('heatLobsters').textContent=String(heatData.totals?.lobsters||0);if($('heatAverage'))$('heatAverage').textContent=Number(heatData.totals?.average||0).toFixed(2);if($('desktopHeatmapBtn'))$('desktopHeatmapBtn').textContent=heatmapVisible?'Dölj':'Visa';const list=$('catchRanking');if(!list)return;const points=[...(heatData.points||[])].sort((a,b)=>(b.avg_catch||0)-(a.avg_catch||0));list.innerHTML=points.length?points.slice(0,30).map((p,index)=>`<button class="desktop-row catch-rank" data-heat-point="${index}"><span class="plan-index">${index+1}</span><span><strong>${esc(p.name||'Område')}</strong><small>${p.check_count} vittjningar · ${p.lobster_count} humrar</small></span><span class="catch-score">${Number(p.avg_catch||0).toFixed(2)}</span></button>`).join(''):'<div class="empty-state"><strong>Ingen fångsthistorik ännu</strong><span>Heatmapen visas först där det finns vittjningar.</span></div>';list.querySelectorAll('[data-heat-point]').forEach(btn=>btn.addEventListener('click',()=>{const p=points[+btn.dataset.heatPoint];if(p)map.easeTo({center:[+p.lon,+p.lat],zoom:14,duration:500})}))}

function renderTrips(){const list=$('desktopTripList');if(!list)return;list.innerHTML=state.trips.length?state.trips.map(t=>`<button class="desktop-row ${historyTripId===t.id?'selected':''}" data-trip-id="${esc(t.id)}"><span class="trip-icon">⌁</span><span><strong>${esc(t.name)}</strong><small>${esc(fmtDay(t.started_at))}${t.ended_at?` · ${Number(t.distance_nm||0).toFixed(1)} NM`:' · pågående'}</small></span><span class="row-distance">${esc(t.actor||'')}</span></button>`).join(''):'<div class="empty-state"><strong>Inga sparade turer</strong><span>Turer du kör i mobilen visas här.</span></div>';list.querySelectorAll('[data-trip-id]').forEach(btn=>btn.addEventListener('click',()=>showHistoryTrack(btn.dataset.tripId)))}

function updateBoat(pos,course){if(!map)return;if(!boatMarker){const el=document.createElement('div');el.className='boat-marker';el.innerHTML='<div class="boat-arrow"></div>';boatMarker=new maptilersdk.Marker({element:el,anchor:'center'}).setLngLat([pos.lon,pos.lat]).addTo(map)}else boatMarker.setLngLat([pos.lon,pos.lat]);const arrow=boatMarker.getElement().querySelector('.boat-arrow');if(arrow&&Number.isFinite(course))arrow.style.transform=`rotate(${course}deg)`}
function handlePosition(position){const c=position.coords,now=position.timestamp||Date.now(),pos={lat:c.latitude,lon:c.longitude};let speed=knots(c.speed),course=Number.isFinite(c.heading)?c.heading:null;if(lastPosition&&now-lastPositionAt>1000){const d=distanceNm(lastPosition,pos),hours=(now-lastPositionAt)/36e5;if(!Number.isFinite(speed)&&hours>0)speed=d/hours;if(!Number.isFinite(course)&&d>.002)course=bearingDeg(lastPosition,pos)}currentPosition=pos;currentAccuracy=Number.isFinite(c.accuracy)?c.accuracy:null;updateBoat(pos,course);$('speedValue').textContent=Number.isFinite(speed)?clamp(speed,0,99).toFixed(1):'0.0';$('courseValue').textContent=Number.isFinite(course)?Math.round(course):'—';$('accuracyValue').textContent=Number.isFinite(c.accuracy)?Math.round(c.accuracy):'—';updateSelectedDistance();updateNavigation();renderTrapList();if(activeTrip){const prev=tripPoints.at(-1),increment=prev?distanceNm(prev,pos):0;if(Number.isFinite(increment)&&increment<.25)tripDistanceNm+=increment;const point={seq:trackSeq++,lat:pos.lat,lon:pos.lon,speed_kn:Number.isFinite(speed)?speed:null,course:Number.isFinite(course)?course:null,accuracy:Number.isFinite(c.accuracy)?c.accuracy:null,recorded_at:new Date(now).toISOString()};tripPoints.push(point);trackBatch.push(point);if(tripPoints.length>12000)tripPoints.splice(0,tripPoints.length-12000);renderTrack();saveActiveTrip();if(trackBatch.length>=12)flushTrackBatch();updateTripUi()}lastPosition=pos;lastPositionAt=now}
function handlePositionError(error){setSync(`GPS: ${error.message||'fel'}`,false)}
function startGps(){if(!navigator.geolocation){toast('GPS stöds inte av den här webbläsaren');return}if(watchId!=null)return;watchId=navigator.geolocation.watchPosition(handlePosition,handlePositionError,{enableHighAccuracy:true,maximumAge:1500,timeout:15000})}
function centerBoat(){if(!currentPosition){toast('Väntar på GPS');startGps();return}map.easeTo({center:[currentPosition.lon,currentPosition.lat],zoom:Math.max(map.getZoom(),NAV_ZOOM),duration:550})}

async function startTrip(){if(activeTrip){openTripSheet();return}const id=crypto.randomUUID(),trip={id,name:`Hummertur ${new Date().toLocaleDateString('sv-SE')}`,started_at:isoNow()};activeTrip=trip;tripPoints=[];trackBatch=[];trackSeq=0;tripDistanceNm=0;saveActiveTrip();$('tripBtn').classList.add('running');$('tripBtnText').textContent='Pågår';await api('POST','/api/trips',trip,{queue:true});toast('Turen startad');centerBoat();updateTripUi()}
function saveActiveTrip(){saveJson(TRIP_KEY,activeTrip?{...activeTrip,tripPoints,trackSeq,tripDistanceNm}:null)}
function restoreActiveTrip(){const stored=loadJson(TRIP_KEY,null);if(!stored||!stored.id)return;activeTrip={id:stored.id,name:stored.name,started_at:stored.started_at};tripPoints=Array.isArray(stored.tripPoints)?stored.tripPoints:[];trackSeq=Number(stored.trackSeq)||tripPoints.length;tripDistanceNm=Number(stored.tripDistanceNm)||0;$('tripBtn').classList.add('running');$('tripBtnText').textContent='Pågår';renderTrack();updateTripUi()}
async function flushTrackBatch(){if(!activeTrip||!trackBatch.length)return;const points=trackBatch.splice(0,trackBatch.length);try{await api('POST',`/api/trips/${encodeURIComponent(activeTrip.id)}/points`,{points},{queue:true})}catch(error){trackBatch.unshift(...points);throw error}}
async function finishTrip(){if(!activeTrip)return;await flushTrackBatch();await api('POST',`/api/trips/${encodeURIComponent(activeTrip.id)}/finish`,{ended_at:isoNow(),distance_nm:tripDistanceNm},{queue:true});const summary=`${tripDistanceNm.toFixed(1)} NM · ${tripPoints.length} GPS-punkter`;activeTrip=null;tripPoints=[];trackBatch=[];trackSeq=0;tripDistanceNm=0;saveJson(TRIP_KEY,null);renderTrack();$('tripBtn').classList.remove('running');$('tripBtnText').textContent='Starta tur';closeSheets();updateTripUi();toast(`Tur sparad · ${summary}`,3600);syncWorkspace({quiet:true})}
function openTripSheet(){if(!activeTrip){startTrip();return}openSheet('tripSheet');updateTripUi()}
function updateTripUi(){$('distanceValue').textContent=tripDistanceNm.toFixed(1);$('tripDistance').textContent=`${tripDistanceNm.toFixed(2)} NM`;$('tripPoints').textContent=String(tripPoints.length);$('tripStarted').textContent=activeTrip?fmtClock(activeTrip.started_at):'—'}

function clearPrivateLocalData(){const keys=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key)keys.push(key)}for(const key of keys)if(key===CACHE_KEY||key===PENDING_KEY||key===TRIP_KEY||key===HEAT_CACHE_KEY||key===AUTH_DEVICE_KEY||key.startsWith(PLAN_CACHE_PREFIX))localStorage.removeItem(key)}
async function logout(){try{await fetch('/api/auth/logout',{method:'POST',headers:{'accept':'application/json'}})}catch{}clearPrivateLocalData();try{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('hummerkartan-')).map(k=>caches.delete(k)))}catch{}try{const regs=await navigator.serviceWorker?.getRegistrations?.();if(regs)await Promise.all(regs.map(r=>r.unregister()))}catch{}location.replace('/login')}

function switchDesktopTab(name){document.querySelectorAll('.desktop-tab').forEach(b=>b.classList.toggle('active',b.dataset.desktopTab===name));document.querySelectorAll('.desktop-pane').forEach(p=>p.classList.toggle('active',p.dataset.desktopPane===name));if(name==='catch'&&!heatData.points?.length)loadHeatmap({quiet:true})}
function bindUi(){
  $('themeBtn').addEventListener('click',()=>setTheme(theme==='night'?'day':'night'));$('desktopThemeBtn').addEventListener('click',()=>setTheme(theme==='night'?'day':'night'));$('centerBtn').addEventListener('click',centerBoat);$('heatmapBtn').addEventListener('click',toggleHeatmap);$('desktopHeatmapBtn').addEventListener('click',toggleHeatmap);
  $('addTrapBtn').addEventListener('click',openNewTrap);$('desktopAddTrapBtn').addEventListener('click',()=>{pendingSpotConversionId=null;beginPlacement('trap')});$('trapsBtn').addEventListener('click',()=>{renderTrapList();openSheet('trapsSheet')});$('mobilePlanBtn').addEventListener('click',openMobilePlan);$('tripBtn').addEventListener('click',()=>activeTrip?openTripSheet():startTrip());$('roundBtn').addEventListener('click',toggleRound);
  $('closeSelectedBtn').addEventListener('click',()=>{selectedTrapId=null;renderSelected();renderDesktopTraps()});$('checkTrapBtn').addEventListener('click',openCheck);$('navigateTrapBtn').addEventListener('click',()=>navigationTarget?.kind==='trap'&&navigationTarget.id===selectedTrapId?stopNavigation():startNavigation());$('editTrapBtn').addEventListener('click',openEditTrap);$('skipTrapBtn').addEventListener('click',skipSelectedTrap);$('retrieveTrapBtn').addEventListener('click',retrieveTrap);
  $('closeSelectedSpotBtn').addEventListener('click',()=>{selectedSpotId=null;renderSelectedSpot();renderPlanOnMap()});$('navigateSpotBtn').addEventListener('click',()=>navigationTarget?.kind==='spot'&&navigationTarget.id===selectedSpotId?stopNavigation():startSpotNavigation());$('setTrapFromSpotBtn').addEventListener('click',openTrapFromSelectedSpot);$('editSpotBtn').addEventListener('click',openSpotEditor);$('skipSpotBtn').addEventListener('click',skipSelectedSpot);$('stopNavBtn').addEventListener('click',stopNavigation);
  $('backdrop').addEventListener('click',closeSheets);document.querySelectorAll('[data-close-sheet]').forEach(b=>b.addEventListener('click',closeSheets));$('cancelPlacementBtn').addEventListener('click',cancelPlacement);$('trapForm').addEventListener('submit',saveTrap);$('checkForm').addEventListener('submit',saveCheck);$('planSpotForm').addEventListener('submit',saveSpotEdit);$('moveSpotMapBtn').addEventListener('click',moveSelectedSpotOnMap);$('spotUseGpsBtn').addEventListener('click',useGpsForSpot);$('deleteSpotBtn').addEventListener('click',deleteSelectedSpot);$('finishTripBtn').addEventListener('click',finishTrip);$('syncBtn').addEventListener('click',()=>syncWorkspace());$('desktopSyncBtn').addEventListener('click',()=>syncWorkspace());
  $('mobileAddSpotBtn').addEventListener('click',()=>beginPlacement('spot',{returnTo:'mobile-plan'}));$('mobileGpsSpotBtn').addEventListener('click',addPlannedSpotAtCurrentPosition);$('mobileFitPlanBtn').addEventListener('click',fitPlanOnMap);$('mobileRefreshPlanBtn').addEventListener('click',refreshCurrentPlan);$('mobileStartRoundBtn').addEventListener('click',startRoundFromPlan);$('mobileSavePlanBtn').addEventListener('click',()=>savePlan());$('mobileAddAllPlanBtn').addEventListener('click',addAllTrapsToPlan);$('mobilePlanDate').addEventListener('change',e=>changePlanDate(e.target.value));
  $('showActiveBtn').addEventListener('click',()=>{filterActiveOnly=true;$('showActiveBtn').classList.add('active');$('showAllBtn').classList.remove('active');renderTraps();renderTrapList()});$('showAllBtn').addEventListener('click',()=>{filterActiveOnly=false;$('showAllBtn').classList.add('active');$('showActiveBtn').classList.remove('active');renderTraps();renderTrapList()});
  $('desktopActiveFilter').addEventListener('click',()=>{desktopFilterActive=true;$('desktopActiveFilter').classList.add('active');$('desktopAllFilter').classList.remove('active');renderDesktopTraps();renderTraps()});$('desktopAllFilter').addEventListener('click',()=>{desktopFilterActive=false;$('desktopAllFilter').classList.add('active');$('desktopActiveFilter').classList.remove('active');renderDesktopTraps();renderTraps()});$('desktopTrapSearch').addEventListener('input',e=>{desktopSearch=e.target.value;renderDesktopTraps()});
  $('exportBtn').addEventListener('click',()=>location.href='/api/export');$('desktopExportBtn').addEventListener('click',()=>location.href='/api/export');$('desktopLogoutBtn').addEventListener('click',logout);$('mobileLogoutBtn').addEventListener('click',logout);document.querySelectorAll('[data-count]').forEach(b=>b.addEventListener('click',()=>{const o=$('lobsterCount'),v=Math.max(0,Number(o.value||o.textContent||0)+Number(b.dataset.count));o.value=String(v);o.textContent=String(v)}));
  document.querySelectorAll('.desktop-tab').forEach(b=>b.addEventListener('click',()=>switchDesktopTab(b.dataset.desktopTab)));$('planDate').addEventListener('change',e=>changePlanDate(e.target.value));$('addPlannedSpotBtn').addEventListener('click',()=>beginPlacement('spot',{returnTo:'desktop-plan'}));$('savePlanBtn').addEventListener('click',()=>savePlan());$('selectAllPlanBtn').addEventListener('click',addAllTrapsToPlan);$('clearHistoryTrackBtn').addEventListener('click',clearHistoryTrack);
  window.addEventListener('online',()=>syncWorkspace({quiet:true}));window.addEventListener('resize',()=>map?.resize());document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncWorkspace({quiet:true})});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(placementMode)cancelPlacement();else closeSheets()}});
}

function handleMapClick(e){if(placementMode==='spot'){addPlannedSpot(e.lngLat);return}if(String(placementMode||'').startsWith('move-spot:')){const id=placementMode.slice(10),spot=dayPlan.items.find(i=>i.id===id&&i.kind==='spot');if(spot){spot.lat=+e.lngLat.lat;spot.lon=+e.lngLat.lng;const ret=endPlacement();selectedSpotId=id;markPlanDirty();updateNavigation();if(ret==='spot-editor')openSpotEditor();toast('Planerad plats flyttad')}return}if(placementMode==='trap'){const p={lat:e.lngLat.lat,lon:e.lngLat.lng};pendingSpotConversionId=null;endPlacement();openNewTrapAt(p);return}if(selectedTrapId||selectedSpotId){selectedTrapId=null;selectedSpotId=null;renderSelected();renderSelectedSpot();renderDesktopTraps();renderPlanOnMap()}}
function initMap(){
  if(!window.maptilersdk){setSync('MapTiler kunde inte laddas',false);return}maptilersdk.config.apiKey=MAPTILER_API_KEY;map=new maptilersdk.Map({container:'map',style:maptilersdk.MapStyle.STREETS,center:WEST_COAST_CENTER,zoom:START_ZOOM,geolocateControl:false,attributionControl:true});map.addControl(new maptilersdk.NavigationControl({showCompass:false}),'bottom-right');
  map.on('load',async()=>{initNauticalDepth(map,MAPTILER_API_KEY,theme);ensureHeatmapLayer();ensurePlanLayer();ensureTrackingLayers();renderTraps();restoreActiveTrip();if(!isDesktop())startGps();await syncState({quiet:true});await Promise.all([loadPlan(localDateKey(),{quiet:true}),loadHeatmap({quiet:true})]);updateHeatmapSource();renderAll()});map.on('click',handleMapClick);
}

bindUi();setTheme(theme);$('planDate').value=localDateKey();$('mobilePlanDate').value=localDateKey();initMap();
syncTimer=setInterval(()=>syncWorkspace({quiet:true}),15000);setInterval(()=>{if(activeTrip)flushTrackBatch()},10000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=2.2.0').catch(()=>{});
